# Generated by Django 5.2.4 on 2025-08-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_product_sale_user_full_name_saleproduct_shop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_after_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
