# Generated by Django 5.2.4 on 2025-08-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_alter_product_price_after_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_create_shops',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='sub_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
