# Generated by Django 5.2.4 on 2025-08-03 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_user_can_create_shops_alter_saleproduct_sub_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopmanager',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops_managed', to=settings.AUTH_USER_MODEL),
        ),
    ]
