# Generated by Django 5.2.4 on 2025-08-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_alter_shopmanager_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managerinvite',
            name='can_edit_managers',
        ),
        migrations.RemoveField(
            model_name='managerinvite',
            name='can_edit_products',
        ),
        migrations.RemoveField(
            model_name='managerinvite',
            name='can_edit_sales',
        ),
        migrations.RemoveField(
            model_name='managerinvite',
            name='can_view_managers',
        ),
        migrations.RemoveField(
            model_name='managerinvite',
            name='can_view_products',
        ),
        migrations.RemoveField(
            model_name='managerinvite',
            name='can_view_sales',
        ),
        migrations.RemoveField(
            model_name='shopmanager',
            name='can_edit_managers',
        ),
        migrations.RemoveField(
            model_name='shopmanager',
            name='can_edit_products',
        ),
        migrations.RemoveField(
            model_name='shopmanager',
            name='can_edit_sales',
        ),
        migrations.RemoveField(
            model_name='shopmanager',
            name='can_view_managers',
        ),
        migrations.RemoveField(
            model_name='shopmanager',
            name='can_view_products',
        ),
        migrations.RemoveField(
            model_name='shopmanager',
            name='can_view_sales',
        ),
        migrations.AddField(
            model_name='managerinvite',
            name='can_manage_managers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='managerinvite',
            name='can_manage_products',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='managerinvite',
            name='can_manage_sales',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='managerinvite',
            name='can_manage_shop_settings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='managerinvite',
            name='can_view_analytics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopmanager',
            name='can_manage_managers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopmanager',
            name='can_manage_products',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopmanager',
            name='can_manage_sales',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopmanager',
            name='can_manage_shop_settings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopmanager',
            name='can_view_analytics',
            field=models.BooleanField(default=False),
        ),
    ]
