# Generated by Django 5.2.4 on 2025-08-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_remove_managerinvite_can_edit_managers_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shopmanager',
            constraint=models.UniqueConstraint(fields=('user', 'shop'), name='unique_user_shop_manager'),
        ),
    ]
