# Generated by Django 5.2.4 on 2025-08-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_alter_product_price_after_discount_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managerinvite',
            name='can_manage_managers',
        ),
        migrations.RemoveField(
            model_name='managerinvite',
            name='can_manage_products',
        ),
        migrations.RemoveField(
            model_name='managerinvite',
            name='can_manage_sales',
        ),
        migrations.RemoveField(
            model_name='managerinvite',
            name='can_manage_shop_settings',
        ),
        migrations.RemoveField(
            model_name='managerinvite',
            name='can_view_analytics',
        ),
        migrations.RemoveField(
            model_name='shopmanager',
            name='can_manage_managers',
        ),
        migrations.RemoveField(
            model_name='shopmanager',
            name='can_manage_products',
        ),
        migrations.RemoveField(
            model_name='shopmanager',
            name='can_manage_sales',
        ),
        migrations.RemoveField(
            model_name='shopmanager',
            name='can_manage_shop_settings',
        ),
        migrations.RemoveField(
            model_name='shopmanager',
            name='can_view_analytics',
        ),
        migrations.AddField(
            model_name='managerinvite',
            name='permissions',
            field=models.JSONField(default={'can_manage_managers': False, 'can_manage_products': False, 'can_manage_sales': False, 'can_manage_shop_settings': False, 'can_view_analytics': False}),
        ),
        migrations.AddField(
            model_name='shopmanager',
            name='permissions',
            field=models.JSONField(default={'can_manage_managers': False, 'can_manage_products': False, 'can_manage_sales': False, 'can_manage_shop_settings': False, 'can_view_analytics': False}),
        ),
    ]
