# Generated by Django 5.2.4 on 2025-08-12 15:50

import pos.permissions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_remove_managerinvite_can_manage_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='managerinvite',
            name='permissions',
            field=models.JSONField(default=pos.permissions.default_permissions),
        ),
        migrations.AlterField(
            model_name='shopmanager',
            name='permissions',
            field=models.JSONField(default=pos.permissions.default_permissions),
        ),
    ]
