# Generated by Django 5.2.4 on 2025-08-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0010_shop_slug_alter_managerinvite_permissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
