# Generated by Django 5.2.4 on 2025-08-12 16:01

from django.db import migrations, models
from django.utils.text import slugify

def populate_slugs(apps, schema_editor):
    Shop = apps.get_model('pos', 'Shop')
    for shop in Shop.objects.all():
        base_slug = slugify(shop.name)
        slug = base_slug
        counter = 1
        while Shop.objects.filter(slug=slug).exclude(id=shop.id).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        shop.slug = slug
        shop.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0012_alter_shop_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.RunPython(populate_slugs),
    ]
