# Generated by Django 5.2.4 on 2025-08-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0013_alter_shop_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
