# Generated by Django 5.2.4 on 2025-08-17 19:29

import pos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0014_alter_shop_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=pos.models.image_upload_to),
        ),
    ]
