# Generated by Django 5.2.4 on 2025-10-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0015_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(choices=[('gray', 'Gray'), ('blue', 'Blue'), ('red', 'Red'), ('green', 'Green'), ('orange', 'Orange'), ('pink', 'Pink')], default='blue', max_length=20),
        ),
    ]
