# Generated by Django 5.2.4 on 2025-10-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0016_category_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('brown', 'Brown'), ('orange', 'Orange')], default='blue', max_length=20),
        ),
    ]
