# Generated by Django 5.2.4 on 2025-10-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0017_alter_category_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reorder_point',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(choices=[('gray', 'Gray'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('brown', 'Brown'), ('orange', 'Orange')], default='blue', max_length=20),
        ),
    ]
